services:
  postgres:
    image: postgres:16-alpine
    container_name: tg-planer-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tg_planer
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
